[2021-06-28 15:20:01,540] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:01,745] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:01,746] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:01,753] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:20:01,754] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:02,116] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): ambassador_channel_partner_tied> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:20:02,244] {standard_task_runner.py:52} INFO - Started process 304 to run task
[2021-06-28 15:20:02,293] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'ambassador_channel_partner_tied', '2021-06-26T23:45:00+00:00', '--job-id', '275', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmpht7uj723', '--error-file', '/tmp/tmp70_7vp_o']
[2021-06-28 15:20:02,298] {standard_task_runner.py:77} INFO - Job 275: Subtask ambassador_channel_partner_tied
[2021-06-28 15:20:03,111] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:20:03,512] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=ambassador_channel_partner_tied
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:20:03,516] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:20:06,661] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:20:17,062] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:20:17,063] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:20:17,111] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=ambassador_channel_partner_tied, execution_date=20210626T234500, start_date=20210628T152001, end_date=20210628T152017
[2021-06-28 15:20:17,237] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:20:17,345] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-28 15:38:19,912] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:38:19,965] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:38:19,966] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:38:19,966] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:38:19,966] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:38:19,989] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): ambassador_channel_partner_tied> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:38:19,998] {standard_task_runner.py:52} INFO - Started process 290 to run task
[2021-06-28 15:38:20,012] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'ambassador_channel_partner_tied', '2021-06-26T23:45:00+00:00', '--job-id', '299', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmpzputv7m2', '--error-file', '/tmp/tmpm1ozsg30']
[2021-06-28 15:38:20,012] {standard_task_runner.py:77} INFO - Job 299: Subtask ambassador_channel_partner_tied
[2021-06-28 15:38:20,165] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.ambassador_channel_partner_tied 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:38:20,334] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=ambassador_channel_partner_tied
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:38:20,337] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:38:22,958] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:38:27,710] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:38:27,711] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:38:27,855] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=ambassador_channel_partner_tied, execution_date=20210626T234500, start_date=20210628T153819, end_date=20210628T153827
[2021-06-28 15:38:28,015] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:38:28,094] {local_task_job.py:151} INFO - Task exited with return code 0
