[2021-06-28 15:20:01,421] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:01,658] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:20:01,659] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:01,659] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:20:01,659] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:20:01,718] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): ambassador_locationbk> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:20:01,786] {standard_task_runner.py:52} INFO - Started process 299 to run task
[2021-06-28 15:20:01,841] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'ambassador_locationbk', '2021-06-26T23:45:00+00:00', '--job-id', '276', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmp6q85vh7t', '--error-file', '/tmp/tmpadnoosit']
[2021-06-28 15:20:01,842] {standard_task_runner.py:77} INFO - Job 276: Subtask ambassador_locationbk
[2021-06-28 15:20:02,622] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:20:03,333] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=ambassador_locationbk
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:20:03,336] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:20:05,427] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:20:07,584] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:20:07,634] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:20:07,882] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=ambassador_locationbk, execution_date=20210626T234500, start_date=20210628T152001, end_date=20210628T152007
[2021-06-28 15:20:08,774] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:20:08,873] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-06-28 15:38:28,754] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:38:28,841] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [queued]>
[2021-06-28 15:38:28,841] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:38:28,841] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-06-28 15:38:28,841] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-28 15:38:28,874] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): ambassador_locationbk> on 2021-06-26T23:45:00+00:00
[2021-06-28 15:38:28,885] {standard_task_runner.py:52} INFO - Started process 309 to run task
[2021-06-28 15:38:28,904] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'ambassador_locationbk', '2021-06-26T23:45:00+00:00', '--job-id', '302', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/analytics_summary.py', '--cfg-path', '/tmp/tmpeejn59ts', '--error-file', '/tmp/tmp8nqk04yh']
[2021-06-28 15:38:28,905] {standard_task_runner.py:77} INFO - Job 302: Subtask ambassador_locationbk
[2021-06-28 15:38:29,196] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.ambassador_locationbk 2021-06-26T23:45:00+00:00 [running]> on host 32c9461fc328
[2021-06-28 15:38:29,422] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=ambassador_locationbk
AIRFLOW_CTX_EXECUTION_DATE=2021-06-26T23:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-26T23:45:00+00:00
[2021-06-28 15:38:29,423] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-28 15:38:31,246] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-28 15:38:32,857] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-28 15:38:32,858] {python.py:151} INFO - Done. Returned value was: None
[2021-06-28 15:38:32,890] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=ambassador_locationbk, execution_date=20210626T234500, start_date=20210628T153828, end_date=20210628T153832
[2021-06-28 15:38:32,965] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-28 15:38:32,986] {local_task_job.py:151} INFO - Task exited with return code 0
