[2021-06-16 13:19:21,992] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.vola_list 2021-06-15T02:30:00+00:00 [queued]>
[2021-06-16 13:19:22,048] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: summary_db.vola_list 2021-06-15T02:30:00+00:00 [queued]>
[2021-06-16 13:19:22,048] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-16 13:19:22,048] {taskinstance.py:1068} INFO - Starting attempt 2 of 5
[2021-06-16 13:19:22,049] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-16 13:19:22,066] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): vola_list> on 2021-06-15T02:30:00+00:00
[2021-06-16 13:19:22,074] {standard_task_runner.py:52} INFO - Started process 2072 to run task
[2021-06-16 13:19:22,082] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'summary_db', 'vola_list', '2021-06-15T02:30:00+00:00', '--job-id', '239', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmvg1hs1u', '--error-file', '/tmp/tmp0f2g5_dx']
[2021-06-16 13:19:22,082] {standard_task_runner.py:77} INFO - Job 239: Subtask vola_list
[2021-06-16 13:19:22,149] {logging_mixin.py:104} INFO - Running <TaskInstance: summary_db.vola_list 2021-06-15T02:30:00+00:00 [running]> on host ac3e7c1eb084
[2021-06-16 13:19:22,287] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=summary_db
AIRFLOW_CTX_TASK_ID=vola_list
AIRFLOW_CTX_EXECUTION_DATE=2021-06-15T02:30:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-15T02:30:00+00:00
[2021-06-16 13:19:22,288] {logging_mixin.py:104} INFO - ------------------------------------Inside Function-----------------------------
[2021-06-16 13:19:24,001] {logging_mixin.py:104} INFO - -------------------------------Data read into dataframe---------------------------
[2021-06-16 13:19:25,920] {logging_mixin.py:104} INFO - ----------------------------------Data written into summary DB----------------------
[2021-06-16 13:19:25,920] {python.py:151} INFO - Done. Returned value was: None
[2021-06-16 13:19:25,937] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=summary_db, task_id=vola_list, execution_date=20210615T023000, start_date=20210616T131921, end_date=20210616T131925
[2021-06-16 13:19:25,995] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-16 13:19:26,025] {local_task_job.py:151} INFO - Task exited with return code 0
